private_diary/diary/urls.py
from django.urls import path

# 同一フォルダ内のviews.pyを参照する
from . import views

app_name = 'diary'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('inquiry/',views.InquiryView.as_view(),name='inquiry'),
    path('diary_list/', views.DiaryListView.as_view(), name='diary_list'),
    
    path('diary_detail/<int:pk>', views.DiaryDetailView.as_view(), name='diary_detail'),
    # <int:pk>はモデル「Diary」クラスで用意されている 主キー値
    path('diary_create/',views.DiaryCreateView.as_view(),name='diary_create'),
    path('diary_update/<int:pk>/',views.DiaryUpdateView.as_view(),name='diary_update'),
    path('diary_delete/<int:pk>/',views.DiaryDeleteView.as_view(),name='diary_delete'),
]


private_diary/private_diary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from . import settings,settings_dev

urlpatterns = [
    path("admin/", admin.site.urls),
    # diaryアプリへのルートを定義する
    # 第一引数はURL上のアプリのフォルダを示す
    # ""はトップフォルダとなる
    path("", include("diary.urls")),
    path("acounts/",include("allauth.urls")),
]

# メディア配信用設定
#   /media/へアクセスしたときに開くフォルダを関連付ける
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

private_diary/diary/models.py
from django.db import models

# ログインユーザ情報
from accounts.models import CustumUser

# Create your models here.

# 新しいモデルを定義したのちにマイグレーションを実行する
# cd privatediary
# python .\manage.py makemigrations
# python .\manage.py migrate

# 日記投稿用モデル
# Diaryクラスを定義する
# class クラス名(継承元クラス): 
class Diary(models.Model):
    # データベースへのフィールド定義
    #   SQLのUPDATE、INSERT INTOで型定義
    # 日記を投稿している人の情報
    user = models.ForeignKey(
        CustumUser,
        verbose_name='ユーザー',
        on_delete=models.PROTECT)
    # 以下 1件分の日記内容
    title = models.CharField(verbose_name='タイトル',max_length=40)
    content = models.TextField(verbose_name='本文',blank=True,null=True)
    photo1 = models.ImageField(verbose_name='写真1',blank=True,null=True)
    photo2 = models.ImageField(verbose_name='写真2',blank=True,null=True)
    photo3 = models.ImageField(verbose_name='写真3',blank=True,null=True)
    # 自動的に処理日時を記録する
    create_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    update_at = models.DateTimeField(verbose_name='更新日時',auto_now=True)


    class Meta:
        verbose_name_plural = 'Diary'

    # オブジェクトを文字列として表す場合の文字列パターン
    # Objectクラスに定義されているメソッド 全てのクラスに存在する
    # →オーバーライドして自分のクラスにあった文字列を返すようにする
    # def __str__(self):
    def __str__(self):
        return self.title

private_diary/diary/forms.py
import os


from django import forms
from django.core.mail import EmailMessage


#
# 問い合わせフォーム
#   入力項目
#       ・お名前            1行文字入力、30文字
#       ・メールアドレス    メールアドレス入力
#       ・タイトル          1行文字入力、30文字
#       ・メッセージ        改行付き文字列
#
class InquiryForm(forms.Form):
    # 入力項目はクラス-フィールド変数として定義する
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)


    # コンストラクタでフィールドに対する詳細定義を行う
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        # 各フォームフィールドエレメントにclass属性とplaceholder属性を設定する
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力して下さい'


        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力して下さい'


        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力して下さい'


        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力して下さい'


    # メールを送信するメソッドを定義する
    def send_mail(self):
        # 承認された入力データを取り出す
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']


        subject = f'お問い合わせ {title}'
        body = f'送信者名: {name}\nメールアドレス: {email}\nメッセージ: {message}\n'
        from_email = os.environ.get('FROM_EMAIL')
        to_list = [from_email]
        cc_list = [email]
        bcc_list = []


        mail = EmailMessage(subject=subject,body=body,to=to_list,cc=cc_list,bcc=bcc_list)
        mail.send()

from .models import Diary

# 日記入力フォーム定義
class DiaryCreateForm(forms.ModelForm):
    # 入力フォームの下になるモデルと使用するフィールドを指定する
    class Meta:
        model = Diary
        fields = ('title','content','photo1','photo2','photo3',)
    
    # コンストラクタ
    #   self     今回生成されたインスタンス
    #   *args    タプルによる引数
    #   **kwargs ディクショナリによる引数
    def __init__(self, *args , ** kwargs):
        # スーパークラスのコンストラクタを呼ぶ
        # → HTMLの基本形が作られる
        super().__init__(*args,**kwargs)
        # 出来た入力エレメントにclass属性を割り当てる
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

private_diary/diary/views.py
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from .forms import InquiryForm

# お問い合わせ送信内容をログに残す
import logging
logger = logging.getLogger(__name__)

# 'アプリ名:url名'からURLを取り出す

# ページ間でメッセージを送る機能

# Create your views here.
# ここにクラスを登録することによりアプリ内の画面を登録する

#   IndexViewクラスはindex.htmlを元にページを構成する

class IndexView(TemplateView):
    template_name = 'index.html'

# お問い合わせページ
class InquiryView(generic.FormView):
    template_name = 'inquiry.html'
    form_class = InquiryForm
    success_url = reverse_lazy('diary:index')


    def form_valid(self, form):
        form.send_mail()
        messages.success(self.request, 'メッセージを送信しました')
        messages.success(self.request, 'CCでメールを同報しています')
        messages.success(self.request, 'ご確認下さいませ')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)
    

from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Diary
from django.core.paginator import Page

# 日記一覧
# ログインが必要で尚且つ一覧表示するViewを継承する
class DiaryListView(LoginRequiredMixin,generic.ListView):
    model = Diary
    template_name = 'diary_list.html'
    paginate_by=2

    # 問い合わせ条件を設定する
    # ※今回は全行ではなくログインしている人の日記のみが対象となる
    def get_queryset(self):
        # Diaryテーブルから条件に当てはまる行を抽出する
        diaries = Diary.objects.filter(user=self.request.user).order_by('create_at')
        return diaries
        # return super().get_queryset()

# 日記を1件表示するビュー
#   DetailViewではpk変数で主キーを受け取る

class DiaryDetailView(LoginRequiredMixin,generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'
# pk_url_kwarg='id'

from .forms import DiaryCreateForm
class DiaryCreateView(LoginRequiredMixin,generic.CreateView):
    model = Diary
    template_name = 'diary_create.html'
    form_class = DiaryCreateForm
    # 登録成功時に表示するページのURL
    success_url = reverse_lazy('diary:diary_list')

    # 登録成功時の処理
    def form_valid (self,form):
        diary = form.save(commit=False)
        # 入力したユーザ情報を保存データに付与する
        diary.user = self.request.user
        # データを保存する
        diary.save()

        # すべて完了したのでテンプレートに送るメッセージをセットする
        messages.success(self.request,'日記を作成しました。')
        return super().form_valid(form)
    
    # 何かの問題で登録が出来なかった場合の処理
    def form_invalid(self, form):
        messages.success(self.request,'日記の作成に失敗しました')
        return super().form_invalid(form)
    
# 既存の日記を編集するビュー
# フォームは新規登録と同じ「DiaryCreateForm」を使用する
# LoginRequiredMixin を継承することによりログインを必要とするビューとなる
# generic.UpdateView を継承することにより既存データを編集するビューとなる
class DiaryUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Diary
    template_name = 'diary_update.html'
    form_class = DiaryCreateForm
    
    # 更新成功後処理
    #   成功した後に表示するページのURLを返す
    def get_success_url(self):
        # 日記詳細ページを開く。この時IDを指定して元々リンクしてきたデータのページを開く
        return reverse_lazy('diary:diary_detail',kwargs={'pk':self.kwargs['pk']})
    
    # 更新成功時の処理
    def form_valid(self, form):
        messages.success(self.request,'日記を更新しました。')
        return super().form_valid(form)
    
    # 更新失敗時の処理
    def form_invalid(self, form):
        messages.error(self.request,'日記の更新に失敗しました。')
        return super().form_invalid(form)
    
# 日記を削除するビュー
class DiaryDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Diary
    template_name = 'diary_delete.html'
    success_url = reverse_lazy('diary:diary_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request,'日記を削除しました')
        return super().delete(request, *args, **kwargs)

private_diary/diary/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="auther" content="">


    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Aoboshi+One&family=Kiwi+Maru&family=M+PLUS+1+Code:wght@100..700&family=M+PLUS+1:wght@100..900&family=Yomogi&family=Yusei+Magic&family=Zen+Kaku+Gothic+New:wght@300;400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="page">
        <!-- Navigation -->
        <nav>
            <div>
                <a href="{% url 'diary:index' %}">
                    <h1>PRIVATE DIARY</h1>
                </a>
            </div>
            <div class="menu">
                <ul>
                    <li><a href="{% url 'diary:inquiry' %}">お問い合わせ</a>　</li>
{% if user.is_authenticated %}
                    <li><a href="{% url 'diary:diary_list' %}">日記一覧</a></li>
                    <li><a href="{% url 'account_logout' %}">Log out</a>　</li>
{% else %}
                    <li><a href="{% url 'account_signup' %}">Sign up</a>　</li>
                    <li><a href="{% url 'account_login' %}">Log in</a></li>
{% endif %}                
                </ul>
            </div>
        </nav>


        <!-- Header -->
        {% block header %}{% endblock %}

        {% if messages %}
        <div class="messages success">
            <ul>
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tag }}" {% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}


        <!-- Contents -->
        {% block contents %}{% endblock %}


        <!-- Footer -->
        <footer>
            <div>Copyright &copy; Private Diary inc. 2024</div>
        </footer>
    </div>
    <!-- JavaScript -->
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

private_diary/diary/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記作成|Private Diary{% endblock %}

{% block contents %}
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">作成</button>
    </form>
</div>
{% endblock %}

private_diary/diary/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集|Private Diary{% endblock %}

{% block contents %}
<div>
    <form method="post">
        {% csrf_token %}
        <p>本当に削除しますか？</p>
        <button type="submit">削除</button>
        <a href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
    </form>
</div>
{% endblock %}

private_diary/diary/templates/diary_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記詳細|private Diary{% endblock %}

{% block contents %}
<div>
    <section>
        <p class="label">タイトル</p>
        <p>{{ object.title }}</p>
    </section>
    <section>
        <p class="label">本文</p>
        <p>{{ object.content|linebreaksbr }}</p>
    </section>
    <section>
        <p class="label">写真</p>
        <p>
            {% if object.photo1 %}
                <img src="{{ object.photo1.url }}" alt="" width="200">
            {% else %}
                <span class="no_image">[no image]</span>
            {% endif %}
        </p>
        <p>
            {% if object.photo2 %}
                <img src="{{ object.photo2.url }}" alt="" width="200">
            {% else %}
                <span class="no_image">[no image]</span>
            {% endif %}
        </p>
        <p>
            {% if object.photo3 %}
                <img src="{{ object.photo3.url }}" alt="" width="200">
            {% else %}
                <span class="no_image">[no image]</span>
            {% endif %}
        </p>
    </section>
    <section>
        <p class="label">作成日時</p>
        <p>{{ object.create_at }}</p>
    </section>
    <section>
        <p class="label">更新日時</p>
        <p>{{ object.update_at }}</p>
    </section>
    <a href="{% url 'diary:diary_update' object.pk %}">編集</a>
    <a href="{% url 'diary:diary_delete' object.pk %}">削除</a>
</div>
{% endblock %}

private_diary/diary/templates/diary_list.html
{% extends 'base.html'%}
{% load static %}

{% block title %}日記一覧 | private Diary {% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div>
    <div>
        <div>
            <h2>
                <a href="{% url 'diary:diary_create' %}">新規作成</a>
            </h2>
        </div>
        {% if is_pagenated %}
            <ul class="paginated">
                {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{page_obj.previous_page_number}}">
                        <span>&nbsp;&laquo;&nbsp;</span>
                    </a>
                </li>
                {% endif %}

                {% for page_num in page_obj.paginator.page_range %}
                    <li>
                        {% if page_num == page_obj.number %}
                            <span class="active">&nbsp;{{ page_num }}&nbsp;</span>
                        {% else %}
                            <a href="?page={{ page_num }}">&nbsp;{{ page_num }}&nbsp;</a>
                        {% endif %}
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li>
                    <a href="?page={{page_obj.next_page_number}}">
                        <span>&nbsp;&raquo;&nbsp;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        {% endif %}

        {% for diary in diary_list %}
            <section>
                <a href="{% url 'diary:diary_detail' diary.pk %}">
                    <h2>{{ diary.title }}</h2>
                    <h3>{{ diary.content|truncatechars:20}}</h3>
                </a>
                <span>{{ diary.created_at }}</span>
            </section>
        {% empty %}
            <p>現在日記はありません</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

private_diary/diary/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集|Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">更新</button>
            <a class="btn btn-secondary ml-2 "href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

private_diary/diary/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Web上に日記を保存できるサービス|Private Diary{% endblock %}


{% block header %}{% endblock %}


{% block contents %}
<section>
    <div>
        <h2>Web Diary</h2>
        <p>Web上で作成/編集/削除ができる日記</p>
    </div>
</section>
<section>
    <div>
        <h2>Save Your Diary</h2>
        <p>あなたの日記をWebに保存</p>
    </div>
</section>
<section>
    <div>
        <h2>Membership System</h2>
        <p>会員制のWeb日記サービス</p>
    </div>
</section>
{% endblock %}

private_diary/diary/templates/inquiry.html
{% extends 'base.html' %}


{% block title %}お問い合わせ|Private Diary{% endblock %}


{% block header %}{% endblock %}


{% block contents %}
<div class="container">
    <form method="post" class="inquiry">
        {% csrf_token %}
        {{ form.non_field_errors }}


        {% for field in form %}
            <section>
                <label for="{{ field.id_for_label }}">
                    <span>{{ field.label }}</span>
                </label>
                {{ field }}
                {{ field.errors }}
            </section>
        {% endfor %}
        <button type='submit'>送信</button>
    </form>
</div>
{% endblock %}